import Head from 'next/head'
import { Text } from "../Components/Text"
import { Number } from "../Components/Number"
import { ContentIcon } from '@/Components/ContentIcon'
import { Container } from '@/Components/Container'
import { Content } from '@/Components/Content'


export default function Home() {
  return (
    <>
      <Head>
        <title>Increment Counter Project Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Content/>
      </Container>
      
      
      




    </>
  )
}
